services:
  optcg-tools:
    container_name: project_optcg-tools
    image: env_generaldev:latest
    pull_policy: missing
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/generaldev/app/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - dependencies:/home/generaldev/.cache
    environment:
      - DISPLAY=${DISPLAY}
volumes:
  dependencies: {}
